version: '3.7'

services:
  regression:
    
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    # Монтирование рабочей директории в контейнер
      - .:/usr/workspace
      # Монтирование папки allure-results для сохранения результатов
      - ./allure-results:/usr/workspace/allure-results

    command: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results"
    working_dir: /usr/workspace
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}